// apps/admins/vue-naive-admin/src/components/BarCode/index.vue
<script setup lang='ts'>
import type { Options } from 'jsbarcode'
import JsBarcode from 'jsbarcode'
import { onMounted, useTemplateRef } from 'vue'

defineOptions({ name: 'BarCode' })

const props = withDefaults(defineProps<Props>(), {
  tag: 'svg',
  text: '',
})

interface Props {
  tag?: 'svg' | 'canvas' | 'img'
  text?: string
  options?: Options
}

const node = useTemplateRef('node')

onMounted(() => {
  JsBarcode(node.value, props.text, props.options)
})
</script>

<template>
  <component :is="tag" ref="node" />
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/components/BarCode/index.tsx
import type { Options } from 'jsbarcode'
import type { CSSProperties, FC } from 'react'
import JsBarcode from 'jsbarcode'
import { useCallback, useEffect, useRef } from 'react'

interface Props {
  tag?: 'svg' | 'canvas' | 'img'
  text: string
  options?: Options
  style?: CSSProperties
  className?: string
}

const BarCode: FC<Props> = ({
  tag = 'svg',
  text,
  options,
  style,
  className,
}) => {
  const containerRef = useRef<never>(null)

  const renderBarcode = useCallback(JsBarcode, [
    text,
    containerRef.current,
    options,
  ])

  useEffect(() => {
    renderBarcode(containerRef.current, text, options)
  }, [renderBarcode, text, options, tag])

  switch (tag) {
    case 'canvas':
      return <canvas ref={containerRef} style={style} className={className} />
    case 'img':
      return (
        <img
          ref={containerRef}
          alt="barcode"
          style={style}
          className={className}
        />
      )
    default:
      return <svg ref={containerRef} style={style} className={className} />
  }
}

export default BarCode
