// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/LangSwitch/index.vue
<script setup lang='ts'>
import type { DropdownDividerOption, DropdownGroupOption, DropdownOption, DropdownRenderOption } from 'naive-ui'
import { $t } from '@/locales'
import { computed } from 'vue'

defineOptions({ name: 'LangSwitch' })

const props = withDefaults(defineProps<Props>(), {
  showTooltip: true,
})

const emit = defineEmits<Emits>()

interface Props {
  lang: App.I18n.LangType
  langOptions: Array<DropdownOption | DropdownGroupOption | DropdownDividerOption | DropdownRenderOption>
  showTooltip?: boolean
}

interface Emits {
  (e: 'changeLang', lang: App.I18n.LangType): void
}

const tooltipContent = computed(() => {
  if (!props.showTooltip)
    return ''

  return $t('header.lang')
})

function changeLang(lang: App.I18n.LangType) {
  emit('changeLang', lang)
}
</script>

<template>
  <n-dropdown :value="lang" :options="langOptions" trigger="hover" @select="changeLang">
    <div>
      <ButtonIcon circle :content="tooltipContent" placement="left">
        <SvgIcon icon="heroicons:language" />
      </ButtonIcon>
    </div>
  </n-dropdown>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/layouts/modules/global-header/components/LangSwitch/index.tsx
import type { FC } from 'react'
import ButtonIcon from '@/components/ButtonIcon'
import { useLang } from '@/hooks/useLang'
import { Dropdown } from 'antd'
import { useTranslation } from 'react-i18next'

interface Props {
  className?: string
  /** Show tooltip */
  showTooltip?: boolean
}

const LangSwitch: FC<Props> = ({ className, showTooltip = true }) => {
  const { t } = useTranslation('header')

  const { locale, localeOptions, changeLocale } = useLang()

  const tooltipContent = showTooltip ? t('lang') : ''

  function changeLocales({ key }: { key: string }) {
    changeLocale(key as App.I18n.LangType)
  }

  return (
    <Dropdown
      menu={{
        items: localeOptions,
        onClick: changeLocales,
        selectedKeys: [locale],
      }}
    >
      <ButtonIcon
        className={className}
        shape="circle"
        icon="heroicons:language"
        tooltipContent={tooltipContent}
        tooltipPlacement="left"
      >
      </ButtonIcon>
    </Dropdown>
  )
}

export default LangSwitch
