// apps/admins/react-antd-admin/src/layouts/modules/global-header/components/ThemeButton/index.tsx
import type { FC } from 'react'
import ButtonIcon from '@/components/ButtonIcon'
import { useAppDispatch } from '@/stores/hook'
import { setThemeDrawerVisible } from '@/stores/modules/app/slice'
import { useTranslation } from 'react-i18next'

interface Props {
  className?: string
  /** Show tooltip */
  showTooltip?: boolean
}

const ThemeButton: FC<Props> = ({ className, showTooltip = true }) => {
  const { t } = useTranslation()

  const tooltipContent = showTooltip ? t('header.themeConfig') : ''

  const dispatch = useAppDispatch()

  function handleClick() {
    dispatch(setThemeDrawerVisible(true))
  }

  return (
    <ButtonIcon
      className={className}
      shape="circle"
      icon="majesticons:color-swatch-line"
      tooltipContent={tooltipContent}
      onClick={handleClick}
    />
  )
}

export default ThemeButton

// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/ThemeButton/index.vue
<script setup lang='ts'>
import { $t } from '@/locales'
import { useAppStore } from '@/stores/modules/app'

defineOptions({ name: 'ThemeButton' })

const appStore = useAppStore()
</script>

<template>
  <ButtonIcon
    circle
    icon="majesticons:color-swatch-line"
    :content="$t('icon.themeConfig')"
    @click="appStore.openThemeDrawer"
  />
</template>

<style scoped>

</style>
