// apps/temps/nuxt-temp/app/components/InputEntry.vue
<script setup lang='ts'>
const name = ref('')

const router = useRouter()

function go() {
  if (name.value)
    router.push(`/hi/${encodeURIComponent(name.value)}`)
}
</script>

<template>
  <div>
    <input
      id="input"
      v-model="name"
      placeholder="What's your name?"
      type="text"
      autocomplete="off"
      p="x-4 y-2" m="t-5" w="250px"
      text="center" bg="transparent"
      border="~ rounded gray-200 dark:gray-700"
      outline="none active:none"
      @keydown.enter="go"
    >
    <div>
      <button
        text-sm btn m-3
        :disabled="!name"
        @click="go"
      >
        GO
      </button>
    </div>
  </div>
</template>

// apps/temps/next-temp/src/components/InputEntry.tsx
'use client'

import { useRouter } from 'next/navigation'
import { useState } from 'react'

function InputEntry() {
  const [name, setName] = useState('')

  const router = useRouter()

  const go = () => {
    if (name) {
      router.push(`/hi/${encodeURIComponent(name)}`)
    }
  }

  return (
    <>
      <input
        className="w-[250px] mt-5 px-4 py-2 rounded text-center border border-gray-200 dark:border-gray-700 bg-transparent outline-none"
        type="text"
        value={name}
        onChange={e => setName(e.target.value)}
        placeholder="What's your name?"
      />
      <div>
        <button className="btn text-sm m-3" disabled={!name} onClick={go}>
          GO
        </button>
      </div>
    </>
  )
}

export default InputEntry
