// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/FullScreen/index.vue
<script setup lang='ts'>
defineOptions({ name: 'FullScreen' })

defineProps<Props>()

interface Props {
  full?: boolean
}
</script>

<template>
  <ButtonIcon :key="String(full)" circle :content="full ? $t('header.fullscreenExit') : $t('header.fullscreen')">
    <icon-gridicons-fullscreen-exit v-if="full" />
    <icon-gridicons-fullscreen v-else />
  </ButtonIcon>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/components/FullScreen/index.tsx
import type { FC } from 'react'
import { useFullscreen } from 'ahooks'
import { useTranslation } from 'react-i18next'
import ButtonIcon from '../ButtonIcon'

interface Props {
  className?: string
  target?: Element | (() => Element)
}

const FullScreen: FC<Props> = ({ className, target = document.body }) => {
  const { t } = useTranslation()

  const [isFullscreen, { toggleFullscreen }] = useFullscreen(target)

  return (
    <ButtonIcon
      shape="circle"
      className={className}
      icon={isFullscreen ? 'gridicons:fullscreen-exit' : 'gridicons:fullscreen'}
      tooltipContent={
        isFullscreen ? t('header.fullscreenExit') : t('header.fullscreen')
      }
      onClick={toggleFullscreen}
    >
    </ButtonIcon>
  )
}

export default FullScreen
