// apps/admins/react-antd-admin/src/layouts/modules/global-header/components/UserAvatar/index.tsx
import type { MenuProps } from 'antd'
import ButtonIcon from '@/components/ButtonIcon'
import SvgIcon from '@/components/SvgIcon'
import { useAppSelector } from '@/stores/hook'
import { getUserInfo } from '@/stores/modules/user/slice'
import { Avatar, Dropdown } from 'antd'
import { useTranslation } from 'react-i18next'

function UserAvatar() {
  const { t } = useTranslation()

  const userInfo = useAppSelector(getUserInfo)

  const items: MenuProps['items'] = [
    {
      key: 'userCenter',
      label: (
        <div className="flex-center gap-8px">
          <SvgIcon className="text-18px" icon="ph:user-circle" />
          {t('common.userCenter')}
        </div>
      ),
    },
    {
      type: 'divider',
    },
    {
      key: 'logout',
      label: (
        <div className="flex-center gap-8px">
          <SvgIcon className="text-18px" icon="ph:sign-out" />
          {t('common.logout')}
        </div>
      ),
    },
  ]

  const onClick = ({ key }: { key: string }) => {
    console.log(key)
  }

  return (
    <Dropdown
      menu={{
        items,
        onClick,
      }}
    >
      <ButtonIcon className="px-8px">
        {userInfo?.avatar
          ? <Avatar size="small" src={userInfo.avatar} />
          : <SvgIcon className="text-2xl" icon="ph:user-circle" />}
        <span className="text-16px font-medium">{userInfo.userName}</span>
      </ButtonIcon>
    </Dropdown>
  )
}

export default UserAvatar

// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/UserAvatar/index.vue
<script setup lang='ts'>
import { $t } from '@/locales'
import { useUserStore } from '@/stores/modules/user'
import { computed } from 'vue'

defineOptions({ name: 'UserAvatar' })

const { userInfo } = useUserStore()

const options = computed(() => ([
  {
    label: $t('header.userCenter'),
    key: 'userCenter',
  },
  {
    type: 'divider',
    key: 'd1',
  },
  {
    label: $t('header.logout'),
    key: 'logout',
  },
]))

function handleSelect() {
}
</script>

<template>
  <n-dropdown
    placement="bottom"
    trigger="click"
    :options="options"
    @select="handleSelect"
  >
    <n-avatar
      round
      class="cursor-pointer"
      :src="userInfo?.avatar"
    >
      <template #fallback>
        <ButtonIcon>
          <SvgIcon icon="ph:user-circle" />
        </ButtonIcon>
      </template>
    </n-avatar>
  </n-dropdown>
</template>

<style scoped>

</style>
