// apps/admins/vue-naive-admin/src/views/feature/chart/echarts/index.vue
<script setup lang='ts'>
import BarCharts from './bar/index.vue'
import LineCharts from './line/index.vue'
</script>

<template>
  <div>
    <NCard title="柱状图" :bordered="false" class="card-wrapper">
      <BarCharts />
    </NCard>
    <NCard title="折线图" :bordered="false" class="card-wrapper">
      <LineCharts />
    </NCard>
  </div>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/pages/feature/chart/echarts/index.tsx
import { Card } from 'antd'
import { useTranslation } from 'react-i18next'

import BarCharts from './bar'
import LineCharts from './line'

function echarts() {
  const { t } = useTranslation('page')

  return (
    <>
      <Card
        className="card-wrapper"
        title={t('feature.chart.bar')}
        variant="borderless"
        size="small"
      >
        <BarCharts />
      </Card>

      <Card
        className="card-wrapper"
        title={t('feature.chart.line')}
        variant="borderless"
        size="small"
      >
        <LineCharts />
      </Card>
    </>
  )
}

export default echarts
