// apps/admins/react-antd-admin/src/pages/about/index.tsx
import { Card, Descriptions, Space } from 'antd'
import { useTranslation } from 'react-i18next'
import pkg from '~/package.json'

interface PkgVersionInfo {
  name: string
  version: string
}

interface PkgJson {
  name: string
  version: string
  dependencies: PkgVersionInfo[]
  devDependencies: PkgVersionInfo[]
}

const { name, version, dependencies, devDependencies } = pkg

function transformVersionData(tuple: [string, string]): PkgVersionInfo {
  const [$name, $version] = tuple
  return {
    name: $name,
    version: $version,
  }
}

const pkgJson: PkgJson = {
  name,
  version,
  dependencies: Object.entries(dependencies).map(item =>
    transformVersionData(item),
  ),
  devDependencies: Object.entries(devDependencies).map(item =>
    transformVersionData(item),
  ),
}

function About() {
  const { t } = useTranslation('page')

  return (
    <Space className="w-full" direction="vertical" size={16}>
      <Card
        className="card-wrapper"
        title={t('about.title')}
        variant="borderless"
        size="small"
      >
        <p>{t('about.introduction')}</p>
      </Card>

      <Card
        className="card-wrapper"
        title={t('about.prdDep')}
        variant="borderless"
        size="small"
      >
        <Descriptions bordered size="small" column={{ xs: 1, sm: 1, md: 2, lg: 2, xl: 2 }}>
          {pkgJson.dependencies.map((item) => {
            return (
              <Descriptions.Item
                key={item.name}
                label={item.name}
                className="text-truncate"
              >
                {item.version}
              </Descriptions.Item>
            )
          })}
        </Descriptions>
      </Card>

      <Card
        className="card-wrapper"
        title={t('about.devDep')}
        variant="borderless"
        size="small"
      >
        <Descriptions bordered size="small" column={{ xs: 1, sm: 1, md: 2, lg: 2, xl: 2 }}>
          {pkgJson.devDependencies.map((item) => {
            return (
              <Descriptions.Item
                key={item.name}
                label={item.name}
                className="text-truncate"
              >
                {item.version}
              </Descriptions.Item>
            )
          })}
        </Descriptions>
      </Card>
    </Space>
  )
}

export default About

// apps/admins/vue-naive-admin/src/views/about/index.vue
<script setup lang='ts'>
import { useAppStore } from '@/stores/modules/app'
import { computed } from 'vue'
import pkg from '~/package.json'

interface PkgVersionInfo {
  name: string
  version: string
}

interface PkgJson {
  name: string
  version: string
  dependencies: PkgVersionInfo[]
  devDependencies: PkgVersionInfo[]
}

const { name, version, dependencies, devDependencies } = pkg

function transformVersionData(tuple: [string, string]): PkgVersionInfo {
  const [$name, $version] = tuple
  return {
    name: $name,
    version: $version,
  }
}

const pkgJson: PkgJson = {
  name,
  version,
  dependencies: Object.entries(dependencies).map(item => transformVersionData(item)),
  devDependencies: Object.entries(devDependencies).map(item => transformVersionData(item)),
}

const appStore = useAppStore()

const column = computed(() => (appStore.isMobile ? 1 : 2))
</script>

<template>
  <NSpace vertical :size="16">
    <NCard :title="$t('page.about.title')" :bordered="false" size="small" segmented class="card-wrapper">
      <p>{{ $t('page.about.introduction') }}</p>
    </NCard>

    <NCard :title="$t('page.about.prdDep')" :bordered="false" size="small" segmented class="card-wrapper">
      <NDescriptions label-placement="left" bordered size="small" :column="column">
        <NDescriptionsItem v-for="item in pkgJson.dependencies" :key="item.name" :label="item.name">
          {{ item.version }}
        </NDescriptionsItem>
      </NDescriptions>
    </NCard>

    <NCard :title="$t('page.about.devDep')" :bordered="false" size="small" segmented class="card-wrapper">
      <NDescriptions label-placement="left" bordered size="small" :column="column">
        <NDescriptionsItem v-for="item in pkgJson.devDependencies" :key="item.name" :label="item.name">
          {{ item.version }}
        </NDescriptionsItem>
      </NDescriptions>
    </NCard>
  </NSpace>
</template>

<style scoped>

</style>
