// apps/admins/react-antd-admin/src/layouts/modules/global-header/components/DarkSwitch/index.tsx
import type { TooltipProps } from 'antd'
import type { FC } from 'react'
import ButtonIcon from '@/components/ButtonIcon'
import { useThemeScheme } from '@/hooks/useThemeScheme'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

interface Props {
  className?: string
  /** Show tooltip */
  showTooltip?: boolean
  /** Tooltip placement */
  tooltipPlacement?: TooltipProps['placement']
}

const icons = {
  light: 'ri:sun-line',
  dark: 'ri:moon-line',
}

const DarkSwitch: FC<Props> = ({
  className,
  showTooltip = true,
  tooltipPlacement = 'bottom',
  ...reset
}) => {
  const { t } = useTranslation()

  const { darkMode, toggleDark } = useThemeScheme()

  const icon = useMemo(() => {
    return darkMode ? icons.dark : icons.light
  }, [darkMode])

  const tooltipContent = showTooltip ? t('header.themeSchema') : ''

  return (
    <ButtonIcon
      shape="circle"
      className={className}
      icon={icon}
      tooltipPlacement={tooltipPlacement}
      tooltipContent={tooltipContent}
      onClick={toggleDark}
      {...reset}
    />
  )
}

export default DarkSwitch

// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/DarkSwitch/index.vue
<script setup lang='ts'>
import type { PopoverPlacement } from 'naive-ui'
import { toggleDark } from '@/composables/dark'
import { $t } from '@/locales'
import { computed } from 'vue'

defineOptions({ name: 'DarkSwitch' })

const props = withDefaults(defineProps<Props>(), {
  showTooltip: true,
  placement: 'bottom',
})

interface Props {
  darkMode: boolean
  showTooltip?: boolean
  placement?: PopoverPlacement
}

const icons = {
  light: 'ri:sun-line',
  dark: 'ri:moon-line',
}

const icon = computed(() => {
  return props.darkMode ? icons.dark : icons.light
})

const content = computed(() => {
  if (!props.showTooltip)
    return ''

  return $t('header.themeSchema')
})
</script>

<template>
  <ButtonIcon circle :icon="icon" :content="content" :placement="placement" @click="toggleDark" />
</template>

<style scoped>

</style>
