// apps/temps/next-temp/src/components/Footer.tsx
import Link from 'next/link'
import { FaGithub, FaHome } from 'react-icons/fa'
import { MdLibraryBooks } from 'react-icons/md'

function Footer() {
  const links = [
    {
      label: 'Home',
      icon: <FaHome />,
      to: '/',
    },
    {
      label: 'Next',
      icon: <MdLibraryBooks />,
      to: 'https://nextjs.org/docs',
    },
    {
      label: 'GitHub',
      icon: <FaGithub />,
      to: 'https://github.com/oOBobbyOo/henry-monorepo/tree/main/apps/temps/next-temp',
    },
  ]

  return (
    <div className="text-2xl m-5 flex justify-center gap-4">
      {links.map((item, i) => {
        return (
          <Link
            href={item.to}
            key={i}
            target={item.to.startsWith('http') ? '_blank' : undefined}
          >
            {item.icon}
          </Link>
        )
      })}
    </div>
  )
}

export default Footer

// apps/temps/nuxt-temp/app/components/Footer.vue
<template>
  <div text="xl gray4" m-5 flex="~ gap3" justify-center>
    <NuxtLink i-carbon-campsite to="/" />
    <NuxtLink i-mdi:sort-numeric-variant to="/count" />
    <NuxtLink i-carbon:user-avatar to="/profile" />
    <NuxtLink i-mdi:alert-box-outline to="/about" />
    <a i-carbon-logo-github href="https://github.com/oOBobbyOo/henry-monorepo/tree/main/apps/temps/nuxt-temp" target="_blank" />
    <DarkToggle />
  </div>
</template>
