// apps/admins/react-antd-admin/src/layouts/modules/global-tabs/components/ButtonTab/index.tsx
import type { FC } from 'react'
import type { Props } from '../PageTab'

import clsx from 'clsx'
import styles from '../PageTab/index.module.css'

const ButtonTab: FC<Props> = ({
  active,
  darkMode,
  className,
  prefix,
  suffix,
  style,
  children,
  ...rest
}) => {
  return (
    <div
      className={clsx(
        'relative inline-flex items-center justify-center gap-4 whitespace-nowrap border border-solid rounded-1 px-3 py-1 cursor-pointer',
        [styles['button-tab']],
        { [styles['button-tab_dark']]: darkMode },
        { [styles['button-tab_active']]: active },
        { [styles['button-tab_active_dark']]: active && darkMode },
        className,
      )}
      style={{ ...style }}
      {...rest}
    >
      {prefix}
      {children}
      {suffix}
    </div>
  )
}

export default ButtonTab

// apps/admins/vue-naive-admin/src/layouts/modules/global-tabs/components/ButtonTab/index.vue
<script setup lang='ts'>
import type { PageTabProps } from '../PageTab/index.vue'
import style from '../PageTab/index.module.css'

defineOptions({ name: 'ButtonTab' })

defineProps<PageTabProps>()
</script>

<template>
  <div
    class="relative inline-flex items-center justify-center gap-4 whitespace-nowrap border-(1px solid) rounded-1 px-3 py-1 cursor-pointer"
    :class="[
      style['button-tab'],
      { [style['button-tab_dark']]: darkMode },
      { [style['button-tab_active']]: active },
      { [style['button-tab_active_dark']]: active && darkMode },
    ]"
  >
    <slot name="prefix" />
    <slot />
    <slot name="suffix" />
  </div>
</template>

<style scoped>

</style>
