// apps/admins/react-antd-admin/src/layouts/mobile-layout/index.tsx
import { useAppDispatch, useAppSelector } from '@/stores/hook'
import { getSiderCollapse, setSiderCollapse } from '@/stores/modules/app/slice'
import { getThemeSettings } from '@/stores/modules/theme/slice'
import { Drawer, Layout } from 'antd'
import GlobalContent from '../modules/global-content'

import GlobalFooter from '../modules/global-footer'
import GlobalHeader from '../modules/global-header'
import GlobalSider from '../modules/global-sider'
import ThemeDrawer from '../modules/theme-drawer'

function MobileLayout() {
  const dispatch = useAppDispatch()
  const siderCollapse = useAppSelector(getSiderCollapse)
  const settings = useAppSelector(getThemeSettings)

  return (
    <Layout className="h-screen">
      <Drawer
        open={siderCollapse}
        placement="left"
        closeIcon={null}
        width={settings.sider.width}
        onClose={() => dispatch(setSiderCollapse(false))}
        styles={{ body: { padding: 0 } }}
      >
        <GlobalSider />
      </Drawer>

      <Layout>
        <ThemeDrawer />
        <GlobalHeader />
        <GlobalContent />
        <GlobalFooter />
      </Layout>
    </Layout>
  )
}

export default MobileLayout

// apps/admins/vue-naive-admin/src/layouts/mobile-layout/index.vue
<script setup lang='ts'>
import { useAppStore } from '@/stores/modules/app'

import { useThemeStore } from '@/stores/modules/theme'
import GlobalContent from '../modules/global-content/index.vue'
import GlobalFooter from '../modules/global-footer/index.vue'
import GlobalHeader from '../modules/global-header/index.vue'
import GlobalSider from '../modules/global-sider/index.vue'
import GlobalTabs from '../modules/global-tabs/index.vue'
import ThemeDrawer from '../modules/theme-drawer/index.vue'

defineOptions({ name: 'MobileLayout' })

const appStore = useAppStore()
const themeStore = useThemeStore()
</script>

<template>
  <NLayout has-sider embedded class="wh-full">
    <NDrawer
      v-model:show="appStore.siderCollapse"
      display-directive="show"
      placement="left"
      :width="themeStore.sider.width"
    >
      <GlobalSider />
    </NDrawer>

    <NLayout embedded content-class="min-h-full flex-col">
      <NLayoutHeader bordered position="absolute" class="z-999">
        <GlobalHeader />
        <GlobalTabs />
      </NLayoutHeader>
      <NLayoutContent
        embedded
        :native-scrollbar="false"
        content-class="size-full"
        class="flex-1 p-t-[100px] p-b-[50px]"
      >
        <GlobalContent />
        <ThemeDrawer />
      </NLayoutContent>
      <NLayoutFooter bordered position="absolute" class="z-999">
        <GlobalFooter />
      </NLayoutFooter>
    </NLayout>
  </NLayout>
</template>

<style scoped></style>
