// apps/admins/react-antd-admin/src/layouts/modules/global-header/components/SiderToggler/index.tsx
import type { FC } from 'react'
import ButtonIcon from '@/components/ButtonIcon'
import { useAppDispatch, useAppSelector } from '@/stores/hook'
import { getSiderCollapse, toggleSiderCollapse } from '@/stores/modules/app/slice'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

interface Props {
  arrowIcon?: boolean
}

type NumberBool = 0 | 1

const icons: Record<NumberBool, Record<NumberBool, string>> = {
  0: {
    0: 'line-md:menu-fold-left',
    1: 'line-md:menu-fold-right',
  },
  1: {
    0: 'ph-caret-double-left-bold',
    1: 'ph-caret-double-right-bold',
  },
}

const SiderToggler: FC<Props> = ({ arrowIcon }) => {
  const { t } = useTranslation('header')

  const dispatch = useAppDispatch()
  const siderCollapse = useAppSelector(getSiderCollapse)

  const isArrowIcon = Number(arrowIcon || false) as NumberBool
  const isCollapsed = Number(siderCollapse || false) as NumberBool

  const icon = useMemo(() => {
    return icons[isArrowIcon][isCollapsed]
  }, [isArrowIcon, isCollapsed])

  return (
    <ButtonIcon
      icon={icon}
      tooltipContent={siderCollapse ? t('expandMenu') : t('collapseMenu')}
      onClick={() => dispatch(toggleSiderCollapse())}
    >
    </ButtonIcon>
  )
}

export default SiderToggler

// apps/admins/vue-naive-admin/src/layouts/modules/global-header/components/SiderToggler/index.vue
<script setup lang='ts'>
import { computed } from 'vue'

defineOptions({ name: 'SiderToggler' })

const props = withDefaults(defineProps<Props>(), {
  arrowIcon: false,
})

interface Props {
  collapsed?: boolean
  arrowIcon?: boolean
  zIndex?: number
}

type NumberBool = 0 | 1

const icon = computed(() => {
  const icons: Record<NumberBool, Record<NumberBool, string>> = {
    0: {
      0: 'line-md:menu-fold-left',
      1: 'line-md:menu-fold-right',
    },
    1: {
      0: 'ph-caret-double-left-bold',
      1: 'ph-caret-double-right-bold',
    },
  }

  const arrowIcon = Number(props.arrowIcon || false) as NumberBool

  const collapsed = Number(props.collapsed || false) as NumberBool

  return icons[arrowIcon][collapsed]
})
</script>

<template>
  <ButtonIcon
    :key="String(collapsed)"
    :content="collapsed ? $t('header.expandMenu') : $t('header.collapseMenu')"
    placement="bottom-start"
  >
    <SvgIcon :icon="icon" />
  </ButtonIcon>
</template>

<style scoped>

</style>
