// apps/admins/vue-naive-admin/src/layouts/modules/theme-drawer/components/PageSetting/index.vue
<script setup lang='ts'>
import { themeAnimateModeOptions } from '@/constants'
import { useThemeStore } from '@/stores/modules/theme'
import SettingItem from '../SettingItem/index.vue'

defineOptions({ name: 'PageSetting' })

const themeStore = useThemeStore()
</script>

<template>
  <NDivider>{{ $t('theme.pageSetting.title') }}</NDivider>
  <TransitionGroup tag="div" name="setting-list" class="flex-col-stretch gap-12px">
    <SettingItem key="animate" :label="$t('theme.pageSetting.animate')">
      <NSwitch v-model:value="themeStore.page.animate" />
    </SettingItem>
    <SettingItem v-if="themeStore.page.animate" key="animateMode" :label="$t('theme.pageSetting.animateMode')">
      <NSelect
        v-model:value="themeStore.page.animateMode"
        :options="themeAnimateModeOptions"
        size="small"
        class="w-120px"
      />
    </SettingItem>
    <SettingItem key="header-height" :label="$t('theme.header.height')">
      <NInputNumber v-model:value="themeStore.header.height" size="small" :step="1" class="w-120px" />
    </SettingItem>
    <SettingItem key="footer-visible" :label="$t('theme.footer.visible')">
      <NSwitch v-model:value="themeStore.footer.visible" />
    </SettingItem>
    <SettingItem v-if="themeStore.footer.visible" key="footer-height" :label="$t('theme.footer.height')">
      <NInputNumber v-model:value="themeStore.footer.height" size="small" :step="1" class="w-120px" />
    </SettingItem>
  </TransitionGroup>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/layouts/modules/theme-drawer/components/PageSetting/index.tsx
import { useThemeScheme } from '@/hooks/useThemeScheme'
import { InputNumber, Switch } from 'antd'
import { useTranslation } from 'react-i18next'
import SettingItem from '../Settingitem'

function PageSetting() {
  const { t } = useTranslation()

  const { themeSettings, changePage, changeHeader, changeFooter }
     = useThemeScheme()

  const isPageAnimate = themeSettings.page.animate

  return (
    <div className="relative flex-col-stretch gap-12px">
      {/* Page */}
      <SettingItem label={t('theme.page.animate')}>
        <Switch
          defaultValue={isPageAnimate}
          onChange={value => changePage({ animate: value })}
        />
      </SettingItem>

      {/* Header */}
      <SettingItem label={t('theme.header.height')}>
        <InputNumber
          className="w-120px"
          defaultValue={themeSettings.header.height}
          onChange={value => changeHeader({ height: value ?? 0 })}
        />
      </SettingItem>

      {/* Footer */}
      <SettingItem label={t('theme.footer.visible')}>
        <Switch
          defaultValue={themeSettings.footer.visible}
          onChange={value => changeFooter({ visible: value })}
        />
      </SettingItem>

      <SettingItem
        label={t('theme.footer.height')}
        show={themeSettings.footer.visible}
      >
        <InputNumber
          className="w-120px"
          defaultValue={themeSettings.footer.height}
          onChange={value => changeFooter({ height: value ?? 0 })}
        />
      </SettingItem>
    </div>
  )
}

export default PageSetting
