// apps/admins/react-antd-admin/src/layouts/modules/global-footer/index.tsx
import { useThemeScheme } from '@/hooks/useThemeScheme'
import { Layout } from 'antd'

const { Footer } = Layout

function GlobalFooter() {
  const { themeSettings } = useThemeScheme()

  return (
    <Footer
      className="global-layout-footer flex-center z-99"
      style={{ height: `${themeSettings.footer.height}px` }}
    >
      Copyright © 2025 by @henry
    </Footer>
  )
}

export default GlobalFooter

// apps/admins/vue-naive-admin/src/layouts/modules/global-footer/index.vue
<script setup lang='ts'>
import { useThemeStore } from '@/stores/modules/theme'
import { computed } from 'vue'

defineOptions({ name: 'GlobalFooter' })

const themeStore = useThemeStore()

const height = computed(() => `${themeStore.footer.height}px`)
</script>

<template>
  <div class="layout-footer flex-center">
    Copyright © 2025 by @henry
  </div>
</template>

<style scoped>
.layout-footer {
  height: v-bind(height);
  box-shadow: var(--hb-footer-shadow);
}
</style>
