// apps/admins/react-antd-admin/src/layouts/modules/global-sider/index.tsx
import { useResponsive } from '@/hooks/useResponsive'
import { useAppDispatch, useAppSelector } from '@/stores/hook'
import { getSiderCollapse, setSiderCollapse } from '@/stores/modules/app/slice'
import { getThemeSettings } from '@/stores/modules/theme/slice'
import { Layout } from 'antd'
import { useMemo } from 'react'
import GlobalLogo from '../global-logo'
import GlobalMenus from '../global-menus'

const { Sider } = Layout

function GlobalSider() {
  const { isMobile } = useResponsive()
  const dispatch = useAppDispatch()
  const siderCollapse = useAppSelector(getSiderCollapse)
  const settings = useAppSelector(getThemeSettings)

  const collapsed = useMemo(() => {
    return isMobile ? false : siderCollapse
  }, [isMobile, siderCollapse])

  return (
    <Sider
      className="global-layout-sider h-full z-100"
      breakpoint="lg"
      onBreakpoint={(broken) => {
        dispatch(setSiderCollapse(broken))
      }}
      trigger={null}
      collapsible
      collapsed={collapsed}
      width={settings.sider.width}
      collapsedWidth={settings.sider.collapsedWidth}
    >
      <div className="h-full flex-col">
        <GlobalLogo collapsed={collapsed} />
        <GlobalMenus collapsed={collapsed} />
      </div>
    </Sider>
  )
}

export default GlobalSider

// apps/admins/vue-naive-admin/src/layouts/modules/global-sider/index.vue
<script setup lang='ts'>
import GlobalLogo from '../global-logo/index.vue'
import GlobalMenus from '../global-menus/index.vue'

defineOptions({ name: 'GlobalSider' })
</script>

<template>
  <div class="layout-sider h-full flex-col">
    <GlobalLogo />
    <n-scrollbar class="flex-1">
      <GlobalMenus />
    </n-scrollbar>
  </div>
</template>

<style scoped></style>
