// apps/admins/vue-naive-admin/src/layouts/modules/theme-drawer/components/DarkMode/index.vue
<script setup lang='ts'>
import { useThemeStore } from '@/stores/modules/theme'
import SettingItem from '../SettingItem/index.vue'

defineOptions({ name: 'DarkMode' })

const themeStore = useThemeStore()

const themeSchemaRecord: Record<Theme.ThemeScheme, string> = {
  light: 'theme.themeSchema.light',
  dark: 'theme.themeSchema.dark',
  auto: 'theme.themeSchema.auto',
}
const icons: Record<Theme.ThemeScheme, string> = {
  light: 'material-symbols:sunny',
  dark: 'material-symbols:nightlight-rounded',
  auto: 'material-symbols:hdr-auto',
}

function handleSegmentChange(value: string | number) {
  themeStore.setThemeScheme(value as Theme.ThemeScheme)
}

function handleGrayscaleChange(value: boolean) {
  themeStore.setGrayscale(value)
}

function handleColourWeaknessChange(value: boolean) {
  themeStore.setColourWeakness(value)
}
</script>

<template>
  <NDivider>{{ $t('theme.themeSchema.title') }}</NDivider>
  <div class="flex-col-stretch gap-4">
    <div class="flex-center">
      <NTabs
        :key="themeStore.themeScheme"
        type="segment"
        class="relative w-214px"
        :value="themeStore.themeScheme"
        @update:value="handleSegmentChange"
      >
        <NTab v-for="(_, key) in themeSchemaRecord" :key="key" :name="key">
          <SvgIcon :icon="icons[key]" class="h-20px" />
        </NTab>
      </NTabs>
    </div>
    <SettingItem :label="$t('theme.grayscale')">
      <NSwitch :value="themeStore.grayscale" @update:value="handleGrayscaleChange" />
    </SettingItem>
    <SettingItem :label="$t('theme.colourWeakness')">
      <NSwitch :value="themeStore.colourWeakness" @update:value="handleColourWeaknessChange" />
    </SettingItem>
  </div>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/layouts/modules/theme-drawer/components/DarkMode/index.tsx
import type { SegmentedOptions } from 'antd/es/segmented'
import SvgIcon from '@/components/SvgIcon'
import { useThemeScheme } from '@/hooks/useThemeScheme'
import { Segmented, Switch } from 'antd'
import { useTranslation } from 'react-i18next'
import SettingItem from '../Settingitem'

const themeSchemaRecord: Record<Theme.ThemeScheme, string> = {
  light: 'themeSchema.light',
  dark: 'themeSchema.dark',
  auto: 'themeSchema.auto',
}

const icons: Record<Theme.ThemeScheme, string> = {
  light: 'material-symbols:sunny',
  dark: 'material-symbols:nightlight-rounded',
  auto: 'material-symbols:hdr-auto',
}

const OPTIONS = Object.entries(themeSchemaRecord).map(([key]) => {
  return {
    label: (
      <div className="w-[70px] flex justify-center">
        <SvgIcon className="h-28px" icon={icons[key as Theme.ThemeScheme]} />
      </div>
    ),
    value: key,
  }
}) as SegmentedOptions<Theme.ThemeScheme>

function DarkMode() {
  const { t } = useTranslation('theme')

  const {
    themeSettings,
    themeScheme,
    changeThemeScheme,
    changeGrayscale,
    changeColourWeakness,
  } = useThemeScheme()

  return (
    <div className="flex-col-stretch gap-16px">
      <div className="i-flex-center">
        <Segmented
          options={OPTIONS}
          value={themeScheme}
          onChange={changeThemeScheme}
        />
      </div>

      <SettingItem label={t('grayscale')}>
        <Switch
          defaultChecked={themeSettings.grayscale}
          onChange={changeGrayscale}
        />
      </SettingItem>

      <SettingItem label={t('colourWeakness')}>
        <Switch
          defaultChecked={themeSettings.colourWeakness}
          onChange={changeColourWeakness}
        />
      </SettingItem>
    </div>
  )
}

export default DarkMode
