// apps/admins/react-antd-admin/src/layouts/modules/theme-drawer/components/Settingitem/index.tsx
import type { FC, PropsWithChildren, ReactNode } from 'react'
import clsx from 'clsx'

type Props = PropsWithChildren<{
  className?: string
  /** Label */
  label: React.ReactNode
  show?: boolean
  suffix?: ReactNode
}>

const SettingItem: FC<Props> = ({
  children,
  className,
  label,
  show = true,
  suffix,
}) => {
  if (!show)
    return null

  return (
    <div className={clsx('w-full flex-y-center justify-between', className)}>
      <div>
        <span className="pr-8px text-base">{label}</span>
        {suffix}
      </div>
      {children}
    </div>
  )
}

export default SettingItem

// apps/admins/vue-naive-admin/src/layouts/modules/theme-drawer/components/SettingItem/index.vue
<script setup lang='ts'>
defineOptions({ name: 'SettingItem' })

defineProps<Props>()

interface Props {
  label: string
}
</script>

<template>
  <div class="w-full flex-y-center justify-between">
    <div>
      <span class="pr-2 text-base">{{ label }}</span>
      <slot name="suffix" />
    </div>
    <slot />
  </div>
</template>

<style scoped>

</style>
