// apps/admins/vue-naive-admin/src/layouts/modules/global-tabs/components/PageTab/index.vue
<script setup lang='ts'>
import { computed } from 'vue'
import ButtonTab from '../ButtonTab/index.vue'
import ChromeTab from '../ChromeTab/index.vue'
import style from './index.module.css'
import { createTabCssVars } from './shard'

defineOptions({ name: 'PageTab' })

const props = withDefaults(defineProps<PageTabProps>(), {
  mode: 'chrome',
  commonClass: 'transition-all-300',
  closable: true,
  activeColor: '#1890ff',
})

const emit = defineEmits<Emits>()

export interface PageTabProps {
  mode?: Theme.ThemeTabMode
  darkMode?: boolean
  commonClass?: string
  chromeClass?: string
  buttonClass?: string
  active?: boolean
  activeColor?: string
  closable?: boolean
}

interface Emits {
  (e: 'close'): void
}

const activeTabComponent = computed(() => {
  const { mode, chromeClass, buttonClass } = props

  const tabComponentMap = {
    chrome: {
      component: ChromeTab,
      class: chromeClass,
    },
    button: {
      component: ButtonTab,
      class: buttonClass,
    },
  }

  return tabComponentMap[mode]
})

const cssVars = computed(() => createTabCssVars(props.activeColor))

const bindProps = computed(() => {
  const { chromeClass: _chromeCls, buttonClass: _btnCls, ...rest } = props

  return rest
})

function handleClose() {
  emit('close')
}
</script>

<template>
  <component
    :is="activeTabComponent.component"
    :class="activeTabComponent.class"
    :style="cssVars"
    v-bind="bindProps"
  >
    <template #prefix>
      <slot name="prefix" />
    </template>
    <slot />
    <template #suffix>
      <slot name="suffix">
        <div
          v-if="closable"
          class="w-4 h-4 inline-flex items-center justify-center rd-50% text-sm"
          :class="[
            style['close-tab'],
          ]"
          @pointerdown.stop="handleClose"
        >
          <SvgIcon icon="mdi:close" />
        </div>
      </slot>
    </template>
  </component>
</template>

<style scoped>

</style>

// apps/admins/react-antd-admin/src/layouts/modules/global-tabs/components/PageTab/index.tsx
import type { CSSProperties, FC, MouseEvent, ReactNode } from 'react'
import clsx from 'clsx'
import ButtonTab from '../ButtonTab'
import ChromeTab from '../ChromeTab'
import styles from './index.module.css'
import { createTabCssVars } from './shared'
import SvgClose from './SvgClose'

export interface Props {
  mode?: Theme.ThemeTabMode
  darkMode?: boolean
  className?: string
  commonClass?: string
  chromeClass?: string
  buttonClass?: string
  active?: boolean
  activeColor?: string
  closable?: boolean
  handleClose?: () => void
  onClick: () => void
  prefix?: ReactNode
  suffix?: ReactNode
  children?: ReactNode
  style?: CSSProperties
}

const PageTab: FC<Props> = ({
  mode = 'chrome',
  darkMode,
  active,
  activeColor = '#1890ff',
  className,
  chromeClass,
  buttonClass,
  closable = true,
  handleClose,
  prefix,
  suffix,
  style,
  children,
  ...rest
}) => {
  const cssVars = createTabCssVars(activeColor) as CSSProperties

  const getActiveTabComponent = {
    chrome: {
      class: chromeClass,
      component: ChromeTab,
    },
    button: {
      class: buttonClass,
      component: ButtonTab,
    },
  }

  const ActiveTabComponent = getActiveTabComponent[mode].component
  const activeClass = getActiveTabComponent[mode].class

  function closeTab(event: MouseEvent<HTMLElement>) {
    event.stopPropagation()
    if (handleClose)
      handleClose()
  }

  const suffixComponent
    = suffix || (closable && <SvgClose className={styles['close-tab']} onClick={closeTab} />)

  return (
    <ActiveTabComponent
      active={active}
      className={clsx(activeClass, className)}
      darkMode={darkMode}
      prefix={prefix}
      suffix={suffixComponent}
      style={{ ...cssVars, ...style }}
      {...rest}
    >
      {children}
    </ActiveTabComponent>
  )
}

export default PageTab
