// apps/admins/react-antd-admin/src/pages/feature/chart/echarts/bar/index.tsx
import type { ReactNode } from 'react'
import { Grid, GridItem } from '@/components/Grid'
import CylinderBar from './CylinderBar'
import PictogramBar from './PictogramBar'

interface Chart {
  id: string
  component: () => ReactNode
}

const charts: Chart[] = [
  { id: 'CylinderBar', component: CylinderBar },
  { id: 'PictogramBar', component: PictogramBar },
]

function BarChart() {
  return (
    <Grid gutter={[16, 24]}>
      {charts.map((item) => {
        const Component = item.component
        return (
          <GridItem key={item.id} span={{ xs: 24, lg: 12 }}>
            <Component />
          </GridItem>
        )
      })}
    </Grid>
  )
}

export default BarChart

// apps/admins/vue-naive-admin/src/views/feature/chart/echarts/bar/index.vue
<script setup lang='ts'>
import type { Component } from 'vue'
import CylinderBar from './CylinderBar.vue'
import PictogramBar from './PictogramBar.vue'

interface Chart {
  id: string
  component: Component
}

const charts: Chart[] = [
  { id: 'CylinderBar', component: CylinderBar },
  { id: 'PictogramBar', component: PictogramBar },
]
</script>

<template>
  <NGrid cols="1 l:2" :x-gap="12" :y-gap="24" responsive="screen" item-responsive>
    <NGi v-for="chart in charts" :key="chart.id">
      <component :is="chart.component" />
    </NGi>
  </NGrid>
</template>

<style scoped>

</style>
